name: Check for typos
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run typos command
      run: ./typos ./CONTRIBUTING.md ./README.md

